### ISSUE TITLE
Add support for using XBMC Commander

### ISSUE THREAD

**Issue by maty974** [boxeehacks/boxeehack#102]
I've used this with an installation of XBMC on MacOSX, and it works pretty fine
http://www.xbmc-commander.com/index.php

Maybe this can be implemented too.

**Comment by boxeehacks** [comment]
Unfortunately this cannot be done. Boxee disabled much of the JSON RPC API that is required for this :(
It's all still there, but the hooks have been commented out in the source code. But since we cannot recompile that code (because of missing SDK parts) we can't reenable this...

As soon as we can compile, we'll definitely make this kind of thing possible (and a LOT more), but for now, the answer is unfortunately no :(

**Comment by maty974** [comment]
oh sad news :(
thanks for your answer ;)
