### ISSUE TITLE
Disable Boot (Start Up Video) Sound?

### ISSUE THREAD

**Issue by war59312** [boxeehacks/boxeehack#14]
Hey,

Any chance of muting the boot (start-up video) sound?

Really tired of it and muting my TV every time gets old.

Thanks,

Will

**Comment by boxeehacks** [comment]
I totally agree! One of the first things I thought of doing as well. Unfortunately the video is in a non-user-writeable section of the BoxeeBox. We can replace that folder with our own version (just like the skin hack), but unfortunately the hack is run AFTER the video, so any hacking stuff starts too late for this.

I'm looking into other ways of getting the hack to start up, and if possible I'll definitely try and do something about this (since it's driving me crazy too), but for now it looks like there's nothing much I can do about it...

**Comment by war59312** [comment]
OK no biggy. Can use this issue to track in case if it becomes feasible down the road.

**Comment by boxeehacks** [comment]
Meh :( ... just tried a few dozen additional methods, but nothing user-executable gets run before the video. Really seems its impossible :(

Closing this issue.
