### ISSUE TITLE
volume change

### ISSUE THREAD

**Issue by gpearl** [boxeehacks/boxeehack#145]
First off great project!

The problem I have is that I can not adjust the sound  with the boxee remote.  This was a problem with the manufacture firmware also.

I do have ' control volume during playback' checked.  
My audio output is set to digital hdmi - And i connect to a pioneer receiver.
When I have the option 'dolby digital capable receiver' check the volume slider shows up but you can not adjust it.
When it is not checked I can adjust volume but then do not get  sorround sound.  Can this be fixed

**Comment by BoxeePlusSupporter** [comment]
thats not a bug or something. if your boxee detects an digital audio codec you cant adjust the volume with your boxee. same for other media stations like xtreamer or on of those hundred brands. for adjusting your volume with "surround sound" you have to use your AV-Receiver ;-)

**Comment by gpearl** [comment]
But why.  Just cause other players do it the same does not mean it is right do not get me wrong that does help but once I have switched to boxee I want a one remote experience

**Comment by boxeehacks** [comment]
Probably because the audio gets sent digitally. Which means the original digital file data gets sent to the TV or receiver. That then decodes and plays it back.

If the boxee were to allow volume control, it would have to do the decoding, modify the audio stream (to lower or increase the volume) then re-encode it, then send it to the TV or receiver, where it would get decoded again.

In addition to it just being rather a lot of steps, it's also difficult because some encoding formats are very processor intensive, also because some 5.1 formats you wouldn't want to change linearly, e.g. your center speaker should probably go down slower than the rest, and because encoding those formats requires licenses, so even if they technically could, they wouldn't necessarily be allowed to.

But most importantly, the big benefit of digital audio is that you send the original audio without modification as far as possible before it gets converted to analog. This has great audio quality benefits. If you're just going to modify it as soon as possible anyway, you'll have a quality reduction which kind of negates the benefit of digital...

But even if all that were not the case. This is also something deeply and firmly inside the Boxee executable, which we cannot modify. So there is no way for us to change this behaviour.
