### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by swetoast** [boxeehacks/boxeehack#148]
Hi guys 

First of all THANK YOU, ive had just about given up on boxee and was prowling thru thier forum when i came over Boxee+, i dropped everything and started reading about it then installed it and its great and i hope that you guys do the work the boxee team failed to do.

the only issue i have so far is that im missing a changelog cause i installed 1.2.2 a few hours ago and then there was an update to 1.3.0 but no changelog so i dont know whats been changed mind including a changelog so we the users can see what changes had been made

Regards 
Peter

ps im really happy that you guys stepped up :D

**Comment by war59312** [comment]
Changelog is up at https://github.com/boxeehacks/boxeehack/pull/147

But yes I agree should be included on boxee screen somewhere. Perhaps on an about/credits screen.

**Comment by boxeehacks** [comment]
The changelog is also on the forums: http://forums.boxee.tv/showthread.php?t=64648

This is something a bit more tricky, because you also then have to deal with getting a good notification path into the app, and also deal with how to store those changelogs along with the version number, and how to concatenate multiple version updates for when a user hasn't updated in a while. For now I'll just update the thread. In the future I'll put a more comprehensive log on boxeeplus.com somewhere.
