### ISSUE TITLE
VPN not working in 1.3.1

### ISSUE THREAD

**Issue by helgeim** [boxeehacks/boxeehack#149]
After 1.3.1 update the VPN dont work, it connects, but cant find/start netflix.

**Comment by recursivemonk** [comment]
yeah, something definitely did not work correctly in the changes to address the VPN MTU fixes and it looks like it has broken the VPN.

I have the same issue, I can connect to the VPN, but my Boxee can't find any of the geolocation aware apps (i.e. Pandora, Netflix).

Furthermore, the MTU tweaks that this is supposed to fix are definitely not being applied after the VPN goes up as eth0 remains untouched at MTU 1500.

I think something didn't work as expected with the symbolic linking that was done in this version.

For testing purposes I undid all the changes that 1.3.1 makes, rebooted, then did the following:

-cp -R /etc/ppp /data/hack
-changed network.sh so it only had the entry for 'mount -o bind /data/hack/ppp /etc/ppp'
-replaced ip-up and ip-down scripts with the ones from 1.3.1

VPN works good and the MTU fix is applied.  

So to make a long story short, the ip-up and ip-down scripts are good!  Something else though is causing a fairly significant VPN issue, but it's late here in my timezone and I have to call it a night.  Might not have time to look into more debugging for another day or two.

**Comment by boxeehacks** [comment]
I've just published an updated version which does the following:

mkdir /data/hack/ppp_mnt
cp -R /etc/ppp/\* /data/hack/ppp_mnt
cp -R /data/hack/ppp/\* /data/hack/ppp_mnt
mount -o bind /data/hack/ppp_mnt /etc/ppp

And of course removed the old symbolic link things. That should pretty much give the exact same results as you have. Let me know if this works!

**Comment by boxeehacks** [comment]
Crap... the ip-up and ip-down never got chmod +x , which was why they were still not running... fixed now in 1.3.3

**Comment by recursivemonk** [comment]
just popped into home for lunch and upgraded to 1.3.3.  Rebooted a few times and  Boxee fails to initiate the VPN connection through the UI at all.  Will try to debug tonight if I can find some time.

**Comment by boxeehacks** [comment]
Could you maybe PM me some VPN settings that I could use to test with? That would make it a hell of a lot easier to fix. Because basically (I think) I'm doing script-wise what you did manually... it should work right? :)

Would really like to get this fixed properly.

**Comment by recursivemonk** [comment]
I sent you a PM with VPN details via the boxee forums.

HOWEVER, I think I have the found the problem and I think your solution works perfectly except there was a minor error in the code you uploaded in the last update.

Look at your post above and you said the final command was:

mount -o bind /data/hack/ppp_mnt /etc/ppp

However, when I look at network.sh in 1.3.3. here on github, it has:

mount -o bind /data/hack/ppp /etc/ppp

So with that incorrect path of ppp instead of ppp_mnt, you bind /etc/ppp to a directory that is missing all the contents and scripts to execute a VPN connection.

I manually changed my network.sh so that it bind to /data/hack/ppp_mnt, rebooted, and lo and behold, the VPN connects, and the MTU sets to eth0 at 1460 and ppp0 at 1400.

\o/

Oh...and I did test...when you drop the VPN, eth0 is restoring to 1500 MTU.

Correct the path on the bind and I think we are golden!  Get the change in and feel free to test it yourself with the VPN details I sent you.

**Comment by boxeehacks** [comment]
ARGH!!! Stupid error! :)

Thanks for the VPN info though. If I ever have to test more then at least I have a way to do so... Updating to 1.3.4 now with this fix in...

**Comment by recursivemonk** [comment]
:+1: 

edit: applied 1.3.4 and VPN is working good!

**Comment by boxeehacks** [comment]
Cool! :) then closing

**Comment by PiteH** [comment]
Still having problems with VPN after last update 1.3.4. Don't get any error but it shut down my Internet connection to the box after pressing connect and I have to reboot it to get it back. Have tried two different VPN connections and they both do the same.

**Comment by dmike3** [comment]
I think I mentioned this on the forum. It appears the re-mount of /etc/ppp is causing the problem. Regardless of the 1.3.1 script which mounted the wrong directory (which I fixed locally) problems still persisted. Looking over all the scripts for the VPN in theory it should work. However, it doesn't. The only fix for now is disabling network.sh from boot.sh.

**Comment by boxeehacks** [comment]
Reopening then. Winedog had success at least; but I'll try myself with a VPN. If you could share your VPN settings via PM or something as well, that would help me in troubleshooting this. (Don't worry, I won't use it to harvest your kidneys and sell them on the black market or something)

**Comment by recursivemonk** [comment]
I saw some strange behavior when trying to use both mike3y's vpn shortcut hack and the remount of /etc/ppp, but i have had no problems with the manual remount of /etc/ppp method.

I can't imagine the MTU changes would be network breaking for anyone. If anything they should make the network more tolerant.  

solitude, feel free to keep using my VPN details for testing.

PiteH, when you connect to the VPN and it shuts down the boxee network.  Can you still telnet into the boxee?

**Comment by PiteH** [comment]
Earlier today my connection broke down and now when i try again it stays up, but i get the error message instead.

**Comment by recursivemonk** [comment]
The error message is that your Boxee is offline, right? Not that you get an error from the VPN connection?

If so, I saw a similar issue crop up when the VPN temp files that Boxee looks at to see what state the VPN is currently in have gone stale.

I managed to resolve this after a few cold restarts and VPN connection connect / disconnects.

I also was also wiping out the entire Boxee plus directory and flushing out all the PPP files from the Boxee data storage areas when testing which might have well cleaned it up for me.

so given that PiteH has gone through the latest iterations of Boxee VPN codes, I'm wondering if he has some stale VPN temp files.

One option is to get him to manually clean the temp files, the other is to have him remove / disable Boxeeplus entirely and do some VPN connect / disconnects through the default UI, confirm that it works and that might flush the stale VPN temp files, then reinstall boxeeplus.

Of course, it could be something else entirely.

at work now, but will try and look into specific commands to run to fully flush the VPN tmp files when I get home tonight

**Comment by boxeehacks** [comment]
Thanks a bunch guys. With the VPN settings some of you gave me I've been able to do some testing.
1. Damn Boxee's VPN code is buggy! With or without the hack, it just sometimes plain doesn't work. And i've had it cause my router to reset a few times as well (actually without the hack always).
2. I've figured out why some people were probably having crashes. Setting the MTU too fast or in the process of connecting was causing massive issues! So I've rewritten most of the script to now accurately detect whether the connection is really up before setting the MTU. It now waits as long as necessary before doing stuff.

Also I no longer set the eth0 MTU... I don't think it's needed, since it only affects the transport to the router, and shouldn't affect VPN settings. It did however affect local video streaming, which was slower with the MTU modification. Could you guys again please test to see if this works for you?

New version 1.3.5 released just now...

**Comment by PiteH** [comment]
That worked beautiful to me. No problems anymore. Thanks for the hard work you all put into this. :)

**Comment by boxeehacks** [comment]
Excellent!

**Comment by recursivemonk** [comment]
That's a fine bit of scripting you have done there, sir.

Seems to be working well for me.  Managed to get the connection up and it kept stable while watching netflix for 15 minutes.

I had stability problems in the past when using an eth0 MTU 1500 and after playing around eth0 1460 proved the most stable. I could never understand why, because I completely agree, the ppp0 MTU should dictate the conditions. Perhaps that issue related to how the code was buggy and your rewrite has improved it overall.

So it all seem good.  I noticed that you that you left in the eth0 MTU change, but just commented it out.  I might suggest you leave it commented out for  the next few versions and I'll keep testing connection stability.  Given the crappy ADSL service we get in NZ and the funky network shortcuts they take, I wouldn't be surprised if my situation is at the extreme end of things.
