### ISSUE TITLE
Movie scrolling slow

### ISSUE THREAD

**Issue by scottybgoode** [boxeehacks/boxeehack#152]
When I scroll through the movies it is much slower with this hack. I just use the standard movie sheets that Boxee automatically pulls, but don't know if its going slower now because Boxee Plus is looking for the other .jpg files it now allows.

**Comment by d4yz** [comment]
are you viewing viewing the 9x3 or the 6x2 view? it is known that the 9x3 is a little slower due to displaying more thumbnails

**Comment by boxeehacks** [comment]
Due to some other tweaks that were done it should actually be faster, not slower in 6x2 mode. The 9x3 mode is slower though since it has to load way more images. Nothing we can do about the speed of any of that though. There is a new view mode coming which in my experience is a lot faster. In the 6x2 it's exactly the same as the original stock firmware, so there is no possibility for speedup there.
