### ISSUE TITLE
new remote commands

### ISSUE THREAD

**Issue by kelmk** [boxeehacks/boxeehack#159]
Since boxee flat out refused to add any new remote commands maybe this is something that can be added now? Mainly I would like commands to jump straight to TV or Movies sections without having to go back to the menu first, The way boxee navigation works makes it impossible to make reliable macros for these types of things,
http://jira.boxee.tv/browse/BOXEE-8206

**Comment by ScottAllyn** [comment]
I believe that the box currently does support _some_ jumps like that; I'll have to check when I get home. I would definitely love to see Boxee+ support a feature-rich set of remote commands, tho!

Solitude, is it now possible to customize the lircmap.xml and keymap.xml files? If so, we can finally incorporate the changes that twistybox was working on! We were sooooo close to getting those incorporated into the Boxee Box when Boxee had a sudden (and completely unexplained) change of heart on the matter and decided that, since the current remote options worked well for them, they were good enough for everyone.

Here's the old forum thread on the subject:

http://forums.boxee.tv/showthread.php?t=29521

Here's the worksheet that twistybox was working on:

https://spreadsheets.google.com/ccc?key=0AlXVOBl0er7tdEZlVmE2NllpNGZTLVBpZzl3SkltUUE&hl=en&authkey=CODAo8sH

**Comment by boxeehacks** [comment]
This could be done. However I don't have another remote than the default Boxee remote, so there is no way for me to test. If someone could develop this, I'd be happy to incorporate it. Could even be done as a standalone plugin with the new plugin system.
