### ISSUE TITLE
Allow "Edit" mode ( delete,move,etc... )

### ISSUE THREAD

**Issue by maty974** [boxeehacks/boxeehack#163]
an **"edit mode"** to allow user to **"delete,move,copy to"** actions on a 
multiple/single file/folder selection.

that could be awesome !

**Comment by michske86** [comment]
I fail to see the point here I think... Isn't that what you use your computer for? The organizing of the files on your HDD/Source? Where would you move something to? A different tv show or movie? I'm confused, but excuse me if I just don't understand where you're going with this one :)

**Comment by maty974** [comment]
Yeah, I know it's a lazy behaviour ...
but sometimes you watch a movie or the end of a serie season,
then you want to delete them from the disk, and to do this you need
to have a computer ... but if we have this kind of actions available
directly in the Boxee interface everything goes easier ! :)

The "copy to" action would be great for copying files from the HDD source to a another 
( friend ) usb disk for example.

**Comment by michske86** [comment]
In my head that sounds like "adding stuff for the sake of adding functions" and I don't see any appeal to the general audience... but that's just my opinion :) And since I can't code, I'm not the one deciding if this gets in or out :D Just venting my thoughts ^^

**Comment by maty974** [comment]
Maybe it's because you have different sources setup than mine, here is my setup:
- Aiport Extreme ( with HDD/Source connected and shared over the network )
- BoxeeBox Wire connected to Airport Extreme

Today, when I want to delete or add a new movie to the hdd I just connect to the disk over the network
from my laptop and do what I want with the files.

But from my opinion, I think it's better to have just one device where you could do those basic operations,
and the principaly concerned device is the BoxeeBox.
If I can avoid to swith on/off my computer just to delete files on the boxee disk, I prefer to do it directly from it,
that's all ...

Maybe it's because I'm really lazy guy :P

**Comment by ducapedia** [comment]
I came to boxeebox from xtreamer sidewinder, and I notice a missing of function like these too.
In Xtreamer I can delete some movie to free space when I finish some movie to my automatic download series and movies (in my DD-WRT).
And right now, I even cant acess to Boxee hard drive with Windows Share (cant connect after 1.3.3).
I have no windows machine to make a "real windows share test"... I'm a linux guy (peraphs implement a NFS server to boxee ? could be great (and faster) than samba/cifs)

**Comment by youngchul76** [comment]
Yes.. I think this function is important.
Not having to remember which movies to delete to free up space on hdd days after watching that movie is a must - just look at wdtv live smp, so convenient.

**Comment by jairofsouza** [comment]
I dont know if it is a good function. I dont like to think that my children or others removed or moved my family files from BB. Today the BB is an "secure environment" avoiding this kind of "bad user behavior".

**Comment by youngchul76** [comment]
I love how you so confidently define 'bad' behaviour.. :)  (I somehow feel like a child who has been naughty).
Gosh, there are so many things your children can stuff up using boxee - trust them a bit?

Date: Sun, 16 Dec 2012 02:40:44 -0800

**Comment by F33db3ck** [comment]
Count me in too, I've got some movies showing up even when they are removed from the directory's and rescanning.

Nice feature to remove them directly from within boxee

**Comment by boxeehacks** [comment]
Really, the device that _adds_ videos should also be the one responsible for _removing_ them. Optionally having such a button added could be interesting for some people, but having to use your computer doesn't seem like a bad thing, because you're already using that to add stuff.

So while I get the convenience of it; a "must have feature" it is not, I think...

Will look into it though, but will probably end up somewhere at the bottom of the to-do list ;)

Also will need to look at where to put that button, because I don't want things to turn into a sideshow attraction ;)

**Comment by boxeehacks** [comment]
Ok have looked at this a bit, but that part of the XBMC functionality is disabled in the executable, and since not everything the Boxee Box does is done when an actual SMB or NFS mount exists this makes this pretty unpredictable. Should be fixed by adding this back into the XBMC part of Boxee. But since we cannot until we have access to the SDK I'm closing this issue...
