### ISSUE TITLE
Wide Series Banners

### ISSUE THREAD

**Issue by F33db3ck** [boxeehacks/boxeehack#206]
Is it possible to integrate Wide Series Banners, that's the only thing i am still missing in Boxee :-)

Like:

http://wiki.team-mediaportal.com/@api/deki/files/2481/=TVSeries_WideBanners.jpg

Regards...

**Comment by boxeehacks** [comment]
Can look into this. Will be a bit problematic though, since the way Boxee scrapes stuff it will always download only posters.

I personally prefer posters a _lot_ though, so this won't be high on my priority list I'm afraid ;) ... but will look into it in the future.

Would then probably be solved in a similar way as the fanart thing (so using a specific name in the folders).

**Comment by ghost** [comment]
facebook share doesn't work anymore for me this day I reconnected trough the boxee box website and reinstald boxee app on facebook didn't work for me can some chek this out if it works for them thanks

**Comment by boxeehacks** [comment]
I you have a problem, make a NEW issue for it. And certainly don't post the same question multiple times under multiple issues! Was a pain in the ass to clean up the last time, so please don't do this again...

**Comment by war59312** [comment]
Just ban the fool please. Getting old!

**Comment by boxeehacks** [comment]
Due to boxee scraping this for now cannot be done easily. Will be reevaluated when we start working on the scraper system.
