### ISSUE TITLE
Scheduled reboot?

### ISSUE THREAD

**Issue by locerson** [boxeehacks/boxeehack#220]
Here is a little background on my issue.  This is the sole system connected to my tv and it is all that is used.  My issue is when it has run for a few days it tends to get locked up.  I understand I could use the new reboot button when I am done for the night, but I am lazy and forgetful. Would it be possible to schedule in a reboot say every night.  The biggest issue I see with that is it would have to only go of there wasn't any other processes being used.  Maybe it could check if the screen saver is running?  This would also greatly help with my second box in my theater, as it can go for a while without use and then when it locks up, it doesn't scan my media. When I go to use it, it generally doesn't have any new additions available and I have to search for them in files.  I really appreciate all that has been done to make this device leaps and bounds better than its own company.  Thanks.

**Comment by diff3** [comment]
Busybox got cron built in, so it's easy to make the boxee box reboot on same time everyday. Not sure about the screensaver 

check https://github.com/boxeehacks/boxeehack/issues/217 for cron

and http://clickmojo.com/code/cron-tutorial.html for a tutorial on cron

**Comment by locerson** [comment]
I did see that you got cron working, but my biggest concern is that I don't want to set up a cronjob for any specific time, then be up watching something and have the box bounce on me.

**Comment by diff3** [comment]
ah, then I guess we have to check ps aux then the screensaver is active, if it is an external program we only need to check for it.

**Comment by locerson** [comment]
I have, and don't see anything that I can determine to be the screen saver.

**Comment by locerson** [comment]
So I have a portion of this set up, just not the check for if I am watching something.  I don't know what process to look for or what have you to tell if there is someone using the box.  I set it up slightly different from how it was listed in the boxee forum.  You can use the -c option to specify the working dir, so I used these steps to set it up instead of remounting /var:

 # mkdir /data/hack/crontabs
 # busybox crontab -c /data/hack/crontabs -e

(in the editor)
0 5 \* \* \* /sbin/reboot
(close the editor)

 # printf "#!/bin/sh\n/data/hack/bin/busybox crond -c /data/hack/crontabs &\n" > /data/hack/cron.sh
 # echo "sh /data/hack/cron.sh &" >> boot.sh

If someone could let me know what to use to determine if someone is actually watching something I would greatly appreciate it.  It would also be cool if someone could code something up to allow for a time selection in the boxee+ settings.  Those things are little over my head.

**Comment by oscahie** [comment]
A further improvement to this would be for the reboot script to be able to save the current view and restore to it after the box has been restarted, so that the user doesn't even notice it happened.

**Comment by boxeehacks** [comment]
Closing this for now; should be moved into plugin development (yay new plugins now on B+ :) ). Detection of screensaver doesn't seem possible since it's all part of the main Boxee process. But checking whether the system is idle (CPU usage) would be a good approach.

**Comment by boxeehacks** [comment]
Will open a plugin repo probably sometime in the future; so that we can manage that kind of stuff there.

**Comment by booyakafoo** [comment]
just fyi.. the instructions above for crontab work perfect, but you need to do a
chmod 777 cron.sh 
This allows cron.sh to be executable and run on bootup.

I noticed that a daily reboot doesn't work unless the hdmi source (TV or Receiver) is turned on.  If it isn't turned on Boxee Box will sit idle waiting to boot up.  Once the TV is turned on the Boxee Box will boot up.  This isn't ideal for me since any new content will not be found in Boxee Box's hourly searches.  So for now I am calling reset.sh to cause the Boxee process to restart.  This seems to work well and haven't had any unresponsive Boxee Boxes since I started this.  I used to have to manually reboot every few days or so and I have 3 that get used constantly.

In addition I enabled syslog level Notice and created a crude script that will check /tmp/root-boxee.log for any recently played media files.  If anything has been played in the last 2 hours it doesn't do the reset and clears the log.  It is the only thing I could think of to determine if the Boxee Box is idle or not.  I also do the reset at 5am so it's not likely that anything would be playing at that time.  I tested lots of different ways to check for idle status, but couldn't find any that worked properly.

**Comment by oscahie** [comment]
That sounds good enough to me. Could you please submit a pull request with the changes? Even if the boxeehacks project won't merge it given that the admin appears to be MIA, but at least others can still make a good use of such feature (I for once am sick of having to manually rebook the box).

**Comment by booyakafoo** [comment]
I'm not really sure how to do that, but my script is here http://pastebin.com/4eF0Q0Cm   

I wouldn't know where to start to integrate this into the GUI.  I'm sure there is a better way to do this, but it seems to be working for me.  Enable debug level "Notice" in System | Advanced settings

Script name is idlereboot.sh, and made it executable with   cron 777 idlereboot.sh

crontab has this.

0 5 \* \* \* /data/hack/idlereboot.sh

Every morning at 5am it checks and runs reset.sh if nothing has played within the last 2 hours.

**Comment by booyakafoo** [comment]
Found a better way to see if the boxee box is idle. 

#echo "{\"jsonrpc\": \"2.0\", \"method\": \"Player.GetActivePlayers\",\"id\": 1}" | nc localhost 9090

This connects to the boxee box jsonrpc port 9090 and issues the command

{"jsonrpc": "2.0", "method": "Player.GetActivePlayers","id": 1}

This command returns the following info..  ( http://developer.boxee.tv/JSON_RPC#Player.GetActivePlayers )

Player.GetActivePlayers
Returns which players are active (available for querying)
Note: AudioPlayer, VideoPlayer and Slideshow methods are only available if there respective player is active, use this function to obtain that information
RESULT
video              boolean    True if video is available, false otherwise
audio              boolean    True if audio is available, false otherwise
picture            boolean    True if pictures are playing, false otherwise
browser            boolean    True if the web browser is running, false otherwise

Actual output... when I was playing a movie

#echo "{\"jsonrpc\": \"2.0\", \"method\": \"Player.GetActivePlayers\",\"id\": 1}" | nc localhost 9090
{"id":1,"jsonrpc":"2.0","result":{"audio":false,"browser":false,"picture":false,"video":true}}

Output when not playing...
#echo "{\"jsonrpc\": \"2.0\", \"method\": \"Player.GetActivePlayers\",\"id\": 1}" | nc localhost 9090
{"id":1,"jsonrpc":"2.0","result":{"audio":false,"browser":false,"picture":false,"video":false}}

That output can be processed in a script to report actual player status.

**Comment by booyakafoo** [comment]
lol. I have spent way to much time playing with such a simple aspect but it is kind of fun.  Also, now that I have a better understanding of the JSON commands, I am going to start working on a webpage that will list all my media and allow users to send items to boxee to play.  

I tested two scripts to check if boxee is idle and runs the reset.sh command.  Hopefully someone could integrate this into the GUI via plugin.

This one check for the word true in the Get Active Players output.  If it exists it doesn't reset.  I'm not sure what would happen if someone left a brower open or an app was left on.  I'm not using this one and didn't feel like testing all the active player variables.  I did test playing Video and Audio and it works.

#!/bin/sh
bstatus=$(echo "{\"jsonrpc\": \"2.0\", \"method\": \"Player.GetActivePlayers\",\"id\": 1}" | nc localhost 9090)
if [[ ! -z $(echo ${bstatus}|grep true) ]]; then
        exit
else
        /data/hack/./reset.sh
fi

This one just check to see if video result is false.  If so it resets boxee box.  My boxee boxes are used primarily for video so this is perfect for me.

#!/bin/sh
bstatus=$(echo "{\"jsonrpc\": \"2.0\", \"method\": \"Player.GetActivePlayers\",\"id\": 1}" | nc 192.168.100.81 9090 | cut -f6 -d, | head -c 13)
if [ $bstatus == \"video\":false ] ; then
        /data/hack/./reset.sh
fi

**Comment by booyakafoo** [comment]
In case anyone is interested.  The scripts above don't seem to improve stability.  I did find a method that has been working for the past 13-17 days.  I have one in my office (17 days uptime) that I use daily for testing a web jukebox front end I am working on.  The high temp cpu one is in my bedroom mounted behind the TV.  We use this one daily for watching TV shows.   The third is in the living room and it gets used a few times a week.  Since I implemented the script below; I haven't had to reboot any of them.  When I want to use them they are available and just work.  I'm sure that since I am posting this they will all be frozen/locked up the next time I try to use them.  lol

#!/bin/sh
bstatus=$(echo "{\"jsonrpc\": \"2.0\", \"method\": \"Player.GetActivePlayers\",\"id\": 1}" | nc localhost 9090 | cut -f6 -d, | head -c 13)  
if [ $bstatus == \"video\":false ] ; then
        echo { \"jsonrpc\": \"2.0\", \"method\": \"Device.Connect\", \"params\":{\"deviceid\": \"main\"}, \"id\": 1}{ \"jsonrpc\": \"2.0\", \"method\": \"XBMC.Quit\", \"params\":{}, \"id\": 1 } | telnet localhost 9090 &> /dev/null
fi

+-----------------------------------------------------+
|               Welcome to Boxee+Hacks                |
+-----------------------------------------------------+

Saturday, 11 May 2013, 06:55:34 PM
Linux 2.6.28 i686

Uptime.............: 17 days, 01h56m02s
Boxee Uptime.......: 0 days, 13h55m21s
IP Addresses.......: 192.168.x.x
Memory.............: 242888kB (Free) / 643508kB (Total)
Load Averages......: 3.22, 3.16, 2.98 (1, 5, 15 min)
Running Processes..: 80
CPU temp...........: 61 c
FAN speed..........: 50 rpm

+-----------------------------------------------------+
|               Welcome to Boxee+Hacks                |
+-----------------------------------------------------+

Saturday, 11 May 2013, 06:59:42 PM
Linux 2.6.28 i686

Uptime.............: 13 days, 14h37m20s
Boxee Uptime.......: 0 days, 14h02m40s
IP Addresses.......: 192.168.x.x
Memory.............: 170556kB (Free) / 643508kB (Total)
Load Averages......: 1.59, 1.52, 1.29 (1, 5, 15 min)
Running Processes..: 75
CPU temp...........: 77 c     <-  LOOK at that CPU temp!!!  :)
FAN speed..........: 50 rpm

+-----------------------------------------------------+
|               Welcome to Boxee+Hacks                |
+-----------------------------------------------------+

Saturday, 11 May 2013, 06:59:48 PM
Linux 2.6.28 i686

Uptime.............: 13 days, 04h05m17s
Boxee Uptime.......: 0 days, 13h59m33s
IP Addresses.......: 192.168.x.x
Memory.............: 152756kB (Free) / 643508kB (Total)
Load Averages......: 1.00, 1.04, 1.08 (1, 5, 15 min)
Running Processes..: 76
CPU temp...........: 52 c
FAN speed..........: 50 rpm

**Comment by jorwex** [comment]
Sorry to revive this thread, but I wanted to comment that the behavior that scottmbritton commented on above (where the Boxee doesn't reboot if the HDMI source of his TV is active) does not seem to affect my TV. When I read it the first time, I assumed it was something in the HDMI spec that the TV was adhering to, but mine obviously doesn't, and happily reboots no matter what the source the TV is switched to. Just thought I'd comment in case others dismissed his method.
