### ISSUE TITLE
Not working on IomegaTV with boxee

### ISSUE THREAD

**Issue by seederp2p** [boxeehacks/boxeehack#243]
So this is not working on Iomega TV.

It would be amazing to get this into Iomega

**Comment by walesmd** [comment]
Iomega utilizes the Boxee software, which is vastly different than the Boxee Box (hardware device using the Boxee software that was further developed). I personally believe it is outside of our scope and this project should focus on the Boxee software as it relates to the Boxee Box.

**Comment by seederp2p** [comment]
Hi.

Is it so different? I tried to install but when the system rebooted it happered to have no changes. The only thing that changed was the hostname "/data/hack/boot.sh" as far as I remember.

Thanks

**Comment by walesmd** [comment]
The reason this works on the Boxee Box is due to a command line injection vulnerability. Basically, when entering `;sh /media/BOXEE/install.sh` we are forcing the Boxee software to execute an invalid statement (due to the initial semicolon at the beginning of the statement) which is basically ignored and then run our own script via the shell. This is an unintended vulnerability within the version of Boxee installed on our devices.

I can not speculate as to the differences between the software on our two devices as I do not own an Iomega TV device. I can say, if after the reboot your hostname was changed to boot.sh - that's a good sign (as that is done by the install script) and if you were to continue with the rest of the instructions (namely confirming the checkbox and reboooting once more) you may very well see Boxee+ installed on that device.

Once again, this is all speculation. I don't have your device in front of me, I've never touched one, hell - didn't even know they exist. If your device burns down into 50 kilos of pure black tar heroin, spewing forth demon spawn from the pits of hell and crawls into your bed at night begging for sweet, sweet love in the voice of Rosie O'Donnel - that's your own fault. Not mine, not anyone here - yours alone.

**Comment by boxeehacks** [comment]
If the hostname changed to /data/hack/boot.sh that means the hack vulnerability itself works. However we don't know the filesystem internals of the IomegaTV with Boxee so can't know for sure if /data even exists and how to work with it. What you could do is run the hack but instead of running install.sh from your usb stick try to run debug.sh. If it works then you should be able to login over telnet. If that works there might be some hope in getting this working in the future.

However none of the devs that are currently working on this have an IomegaTV so it will mean quite some work on your part as well.

For now closing the issue because our focus is on the Boxee Box. Would love to help though if I can to get it running on more...
