### ISSUE TITLE
Some TV Shows not showing fanart

### ISSUE THREAD

**Issue by smallclone** [boxeehacks/boxeehack#283]
I have ripped versions of Modern Family and Family Guy. Both massive shows - but the fanart just will not show up in any view.

I also have obscure BBC comedy shows that DO have fanart showing

any advice?

Thanks

**Comment by boxeehacks** [comment]
Can you show me the folder structure you're using for those specific shows (exact file and folder names)?
Make sure the file is called fanart.jpg (needs to be exact, including capitals both in the first part and the extension). And also make sure that you have your seasons grouped under the show folder (so have a folder named "Season 1", "Season 2", etc. in your "Family Guy" folder and have the video files in those season folders), otherwise it will not work.

**Comment by prodriguezii** [comment]
As an FYI

Fanart shows up for all my movies except for those in rar stacks. Folder structure is as follows

Movie
- Movie.r00
- Movie.r01
  ...
- Movie.r15
- fanart.jpg
- folder.jpg
- Movie.nfo

Boxee plays the movie fine, displays the custom cover art and nfo, but does not display the fanart.

**Comment by crax83** [comment]
prodriguezii if you want fanart for movies in rar archives you can do something like this: https://github.com/boxeehacks/boxeehack/issues/318#issuecomment-12194063

That code will however make fanart stop working for movies without rars. So you'll have to recode it to check if the path begins with rar:// or not if you have unpacked movies. I didn't bother to code that since all my movies are rar'd. It wont work with rar'd tv shows and movies in multiple parts (subdirectories e.g. CD1, CD2) at the moment either, I'm gonna look into that when I have a few minutes to spare.

**Comment by jedi76** [comment]
Hello!
I also experience trouble in showing fanart for TV shows. All my movies work excellent but none of my TV shows. I have followed your instruction as mention above but it still wont work....

**Comment by boxeehacks** [comment]
rar files do support fanart, however boxee internally treats a rar file as a directory. So e.g. there's an avi in foo.rar:

somedir/foo.rar/foo.avi

So you need to place fanart in the same folder:

somedir/foo.rar/fanart.jpg

Which means putting it into the rar file. Better to just expand your rar files, because boxee support for it is quite weird, and these are things that we cannot easily work around.
