### ISSUE TITLE
Boxee's incompatibility with 4k Advanced Format Drives

### ISSUE THREAD

**Issue by rangr514** [boxeehacks/boxeehack#288]
Would be great if this problem could be lifted.  I've contacted boxee a few times and scoured forums for workarounds and solutions that could fix the local limitations.  Could this be something that could possibly be worked on? Do you think boxee would still be working on a solution? Wish i could help.

![Thumbs-up-icon](https://f.cloud.github.com/assets/3159484/36745/7e44897a-536b-11e2-9bc6-b2566f7c49a3.png)

**Comment by drunkwithpower** [comment]
Boxee mentioned this would require a core update and rewriting a lot of the existing code to allow for it.  Since the hack doesn't allow for this I am pretty sure we will never see large drives on Boxee unless someone gets a dev kit and a lot of spare time...

**Comment by boxeehacks** [comment]
This limitation is part of the Boxee OS kernel. Which requires the Intel SDK to recompile and get up and running with a newer version. Even if we had the current Intel SDK it would still not work, because the SDK is very old and no longer compatible with the latest kernel (which is needed to support this). Updating the SDK would also break a lot of dependencies (stuff has changed significantly over the years).

All this is very theoretical though, since we don't have any way to access that SDK which means we can't change that kind of stuff at all...

**Comment by boxeehacks** [comment]
Boxee has already mentioned that they will only bring one final (minor) update. I'm fairly certain that update will not contain a fix for this...
