### ISSUE TITLE
Netflix not working for me

### ISSUE THREAD

**Issue by louout** [boxeehacks/boxeehack#289]
Hi 

Unable to get Netflix to work. I've downloaded the app and signed in but this message comes up.

"Unable to connect to Netflix. Please try again or visit www.netflix.com/help" ui-107

Is this just a Uk issue.

**Comment by ducapedia** [comment]
Netflix does not work in boxeebox out of USA... even if your coutry has officaly netflix service (that occurs in my country too.. Brazil.. I only can watch Netflix in my Xbox or PS3 or even in my smartv.. but not in Boxee)

**Comment by ducapedia** [comment]
Of course.. if you use a VPN you could login in netflix service, but not of that in your country (USA service for exemple.. without your subtitles language or your local contents)

**Comment by cacildo** [comment]
Isnt there any way to change that with the hack?

I mean (and that will sound pretty stupid), somehow "copy" the Ps3 netflix app and apply it to boxee using the hack?

The netflix app is never too big. The FTP access on boxeePlus leads to a folder named "Netflix"... isnt there any way to make it work out of US?

**Comment by boxeehacks** [comment]
The netflix app does not work in UK, only with a US account.

And you cannot copy another one, since it needs to have specific code in there to work with the Boxee Box hardware (the graphics chip, the CPU, the remote, etc. etc.). This is not a fixable thing.

**Comment by trevorheisler** [comment]
I'm in Canada and Netflix worked fine on my Boxee Box until I downloaded the Boxee Plus hack two days ago. Now Netflix does not work on my Box. Netflix works fine on my laptop and netbook. However, when I click on the app on the Boxee Box now, it just returns me to the Apps page. When I check my Boxee account I no longer see Netflix under the Services tab. The Box is also no longer showing under my connected devices when I log into my Netflix account on my laptop. And I am not presented with an activation code when I try clicking on the app on the Box. What happened???

Trevor

**Comment by ducapedia** [comment]
Netflix work natively here in Brazil.. including local programation and contents. Works withou VPN in PS3, Xbox360, Web, Android, SmartTV,.... (https://signup.netflix.com/?locale=pt-BR)
But in Boxee the app doesnt appear in list to install. DLink Support says theres nothing to do, because NetflixTeam didnt licensed netflix by boxeebox outsite USA.
I dont know how this works, becouse, is not by local IP (else if, Netflix will didnot work in PS3, Xbox etc). Maybe by ProductID ? (when product pass by ANATEL aproval to sell here in Brazil they block these list of numbers sended to here ?)
I see in boxee config, inside "services" a NETFLIX ID or something.. could be by this too.. I dont Know.
What I said are, if you use VPN on Boxeebox only, the netflix APP will apear to install, but only work when you're under VPN.. and you'll only get Netflix USA (not the Brazilian one).

**Comment by trevorheisler** [comment]
I should not have those issues as Boxee supports Netflix in the USA and Canada. I did a factory restore and it works again.

**Comment by cacildo** [comment]
Im sorry to ask it again, but 1) i do feel i choose my words poorly in my previous coment and 2) are we really sure it isnt possible to "unlock" boxee netflix to regions other than US and Canada? I mean, the app is all there, Brasil, UK  we all have native netflix.... it feels it needs just to "unlock" it for boxee

**Comment by trevorheisler** [comment]
I don't know. Someone may be able to develop a work-around for it.

**Comment by ducapedia** [comment]
Using a VPN or a tunnel you will able to watch netflix with USA contents
