### ISSUE TITLE
will not download

### ISSUE THREAD

**Issue by macd20** [boxeehacks/boxeehack#314]
have followed the instructions to a t and i am not having any luck getting the hack to install. is there a setting that i could possibly be missing? i did the format in fat32 thinking that could be the problem and still no luck. The name is BOXEE. Has anyone had the same issues that would have some advice? thanks

**Comment by cardassian-tailor** [comment]
I see that you closed and re-opened the issue, are you still experiencing the same troubles?

**Comment by macd20** [comment]
yes. thought i was closeing the page sorry. i have still not had any luck

**Comment by D34dmeat** [comment]
Did you put the contents of the install folder in the root directory of your memory stick?
And can you repeat what you entered in the boxee server page.

**Comment by macd20** [comment]
I will try that with the root on the usb. And you mean retry the hack by" And can you repeat what you entered in the boxee server page"?

**Comment by D34dmeat** [comment]
What i meant to say was can you post it here, but you can retry the installation as many times as you want. 

Did you remember to check your server page afterwards so that all server options were still activated cause if you just activated windows sharing before entering the hack boxee will reboot without saving and you'll have to activate it again afterwards

**Comment by macd20** [comment]
think i got it. thank you for all your help. the file wasnt open far enough. i didnt put the had to open the file one more step. i need to learn to follow instructions. thanks you
