### ISSUE TITLE
fanart not working when having rar archives

### ISSUE THREAD

**Issue by apropl** [boxeehacks/boxeehack#318]
Im having rar archives in my media collection and this does not seem to work good with the fanart feature. I have used ember media manager to scrape my entire collection and place fanart.jpg , poster.jpg aso. for all my movies / tv shows. But since i am using rar archives, the fanart hack thinks that the fanart file is located in the rar file instead of the actual folder.
Is this an known issue?

**Comment by boxeehacks** [comment]
Boxee sees a video in a rar file as:

smb://somewhere/somepath/MyMovie.rar/MyMovie.mkv

So for it to work the fanart.jpg would need to be in:

smb://somewhere/somepath/MyMovie.rar/fanart.jpg

This means the fanart and other files need to be IN the rar to work. Much better would be to simply unrar the files and organise the folder structure as suggested in the FAQ.

**Comment by boxeehacks** [comment]
There is not much we can do about this, and time is better spent elsewhere for now...

**Comment by crax83** [comment]
I know this issue is closed, but those of you who still want to have fanart and use rar archived movies you can do the following.
Bear in mind that even though I'm a programmer by profession I'm not a python coder, so this may not be the most efficient way to handle this in. I just wanted to have it done. Also I take no responsibility whatsoever for this code. It might mess up your boxee, but I find it highly unlikely. But use it at your own risk.

Second, I did this for version 1.4.1, if you have another version this might or might not work for you. That being said, here are the steps I did to make this happen:
A. telnet into the boxee (read the wiki/faq about how to do this)
B. nano boxee/skin/boxee/720p/scripts/boxeehack_grab_fanart.py (or use vi if you prefer)
C. search for fanart.jpg and you should find a row that looks like this:

```
        art = path[0:path.rfind("/")+1] + "fanart.jpg"
```

D. replace that row with these rows:

```

        tmpPath = path
        tmpPath = tmpPath.replace("%2d","-")
        tmpPath = tmpPath.replace("%2e",".")
        tmpPath = tmpPath.replace("%2f","/")
        tmpPath = tmpPath.replace("%3a",":")
        tmpPath = tmpPath.replace("%5f","_")
        tmpPath = tmpPath[6:]
        tmpPath = tmpPath[0:tmpPath.rfind("/")]
        art = tmpPath[0:tmpPath.rfind("/")+1] + "fanart.jpg"

```

E. You might have to restart boxee, clear thumbnail cache or reload skin in the Boxee+ settings for this change to take effect.

Please note that this code will only work for movies in rar archives. Movies that aren't in rar archives will not be able to have fanart any more. This shouldn't be that hard to work around though, if you wanted to. Also this code will not work for TV shows at the moment. I might look in to that later.

For those of you who are interested in knowing what this code does it's the following:
The original code looked for the fanart.jpg inside of the rar archive. The data in path variable looks something like this (if you use smb): "rar://smb%3a%2f%2fHOST%2fPATH%2fTO%2fTHE%2fMOVIE%2fmy%2dmovie%2erar/fanart.jpg".
What my code does is that it removes the rar:// in the beginning and replaces the encoded characters to normal ascii. I think these characters should be enough for most people but if not, just add another replace with your character, i.e. %20 for a space. It also removes the everything after the last folder. Using my code the path above looks like this: "smb://HOST/PATH/TO/THE/MOVIE/fanart.jpg".

Hope this makes somebody happy and if you can make my code better please let me know :)
