### ISSUE TITLE
Version check based on revision

### ISSUE THREAD

**Issue by jerbob92** [boxeehacks/boxeehack#34]
As we are moving forward to an auto-updater(or at least an updater). 
I would recommend doing the version checking based on the revision. 

I would also recommend using a seperate "development" branch, and merge back to master when it's ready to get pushed to users.

(maybe we could also make the hack a "git clone" on the boxee itself? Updating from a script would be easier then too)

**Comment by boxeehacks** [comment]
I initially did that (using git clone). But doing it with git requires a shitload of additional libraries to work properly. If git doesn't have all the required dependencies it will checkout the project in a kind of simplified http mode. The resulting git repo however then is not updateable :(

I'm currently looking into doing something similar with SVN, since github also has a read-only SVN checkout, which can be updated much more easily, and it will also allow us to only checkout the part that is needed (just the hack folder).

I don't want to spend too much time on an updater right now though, because I'm working on an entirely different install mechanism (using the other exploit I mentioned). But want to keep that under wraps until after the final version is released.

**Comment by boxeehacks** [comment]
The current version btw is quite stable. So I'm moving all main development to a development branch as you also mentioned. That will make merging changes a bit easier as well.

For most users it's probably enough to know whether the version online is different (because that would almost always mean it's newer). However during dev, it might sometimes be the case that the version on the box is from the dev branch, making it newer than the published version. If you only have a revision hash to work from then I don't know how to differentiate between those scenarios. If we have a full git client on the box, we can easily check through that of course, but due to the dependencies on the ssl stuff that doesn't work yet, which is why I'm using regular version numbers right now.

We can always change this later if it makes sense.
