### ISSUE TITLE
Shared on Twitter or FB

### ISSUE THREAD

**Issue by enguel0314** [boxeehacks/boxeehack#346]
Recreate the ability to shared comments about movies or TV show via twitter or Facebook from BB. this options working properly but now is not working

**Comment by boxeehacks** [comment]
This is an issue with the Boxee servers and not something we can fix (yet). There are some plans for the future for seeing if replacing that server is feasible, but that will take quite a while. If we replace the server then this may become possible again. Otherwise wait till Boxee fixes it themselves...
