### ISSUE TITLE
Development Plans?

### ISSUE THREAD

**Issue by dave-505** [boxeehacks/boxeehack#351]
Can you provide some info on what would be reasonable to expect in terms of development plans for Boxee+ ?

I just got the Boxee Box for Christmas, and wonder if it I will be able to play most of the videos I want to watch using it.  I am disappointed that I cannot watch The Daily Show or most PBS shows due to the version of Flash available.

I see that after 11.2, Linux Flash updates will be limited to Chrome:  http://blogs.adobe.com/flashplayer/2012/02/adobe-and-google-partnering-for-flash-player-on-linux.html
Do you plan to make Chrome available on the Boxee Box?

**Comment by d4yz** [comment]
Well the boxee box has reached end of life and the Boxee team stated they will do a final update which would include the new flash version. They said they would give us an status update in December which never happened. Since we dont have the ce4100 sdk we cant compile our own version of boxee box or update the flash. this is something that will just have to wait on

**Comment by nick-desteffen** [comment]
http://old-blog.boxee.tv/2012/12/07/flash-11-update-for-boxee-box/#.UO7kr4xVuGo

Looks like they posted something, surprisingly... Nothing useful though.

**Comment by dave-505** [comment]
d4yz, you said: "Since we dont have the ce4100 sdk we cant compile our own version of boxee box or update the flash. this is something that will just have to wait on"  Are you saying that the development plans for Boxee+ are unclear because you do not know if you will ever be able  to compile a new version?

**Comment by war59312** [comment]
Either way, a list of doable "goals" should be made public perhaps. ;)

**Comment by boxeehacks** [comment]
Yes when Boxee releases their final version, we will make sure either this hack gets updated for that version, or we include the flashplayer from that version into the hack.

However we cannot (due to missing SDKs) expand what kind of videos the Boxee Box plays ourselves. So whatever it plays that's it. We can only try to improve the experience around it (with things like fanart, watched status, etc. etc.)

I'll post something about goals 'n' stuff on the website sometime in the future. However it's really not that well defined yet. It's growing pretty organically, based on the needs that I and many of you had for this Box, while trying to keep true to the core experience of Boxee. For me that meant Music & Fanart, but for other people (as you can see in the requests in here) it means different things...
