### ISSUE TITLE
IPad screen duplication

### ISSUE THREAD

**Issue by srednao** [boxeehacks/boxeehack#366]
Is there any chance that Boxee+ will support iOS screen duplication in the same way as apple tv does (over AirPlay).

**Comment by felixekman** [comment]
Probably not, as it is not yet done for XBMC.

**Comment by boxeehacks** [comment]
Nope. Even if XBMC supports it fully at some time, we still cannot make our own version because we need the Intel SDK for the Boxee Box to compile it. Only possibility would be for Boxee Inc. to create and release this feature, however they have already mentioned that we won't be getting any new features anymore except for Flash 11.
