### ISSUE TITLE
Several Issues during movie playback.

### ISSUE THREAD

**Issue by ldbrenes** [boxeehacks/boxeehack#383]
I have been having problems playing movies, some of them loose audio and the only way to get it back is to exit the movie and then start it again from where I was.

other movies I will be watching and they will randomly stop sending me back to the movie selection then I have to resume the movie.

This has happened with AVI files and MKV and it used not to happen before B+

Also I have noticed that AAC 5.1 is not working.

It will be nice to be able to select different identifier sources like on XBMC, XBMC is much better identifying concerts and movies without NFO files.

**Comment by boxeehacks** [comment]
Identifiers (or Scrapers as they are called) is something which already has another issue for it open already, so please look at that.

As far as file playback, we cannot change the way that Boxee plays back videos and audio. If a video is not supported then we won't be able to add support unfortunately. This is due to a required Intel SDK that we cannot get access to...
