### ISSUE TITLE
Fanart without Moviefolders

### ISSUE THREAD

**Issue by DerMario-zz** [boxeehacks/boxeehack#421]
It would be great if the boxee could recognize Movie fanart in a folder with many movies. 
Example:

Movie A.jpg
Movie A.mkv
Movie A-fanart.jpg
Movie A.nfo
Movie B.jpg
Movie B.mkv
Movie B-fanart.jpg
Movie B.nfo
.
.
.

**Comment by dcoleman5423** [comment]
@DerMario 
I agree.... It would be nice to have the Boxee pull the Fanart just as it does on the coverart. It would be nice to have it store the coverart and fanart in a folder an external HD or even the SD slot/card.
For Example: My hacked Wii does this.

**Comment by boxeehacks** [comment]
This is not likely to ever happen, since most tools for managing your movies enforce the movies in folder standard and I don't want to spend time and effort for a non-standard way of working. It's something I can't test very well either (because I don't have such a structure), and it's very easy to migrate to the correct folder structure (most software tools for managing NFO's contain a feature to do this automatically.
