### ISSUE TITLE
fanart not working

### ISSUE THREAD

**Issue by rdlm** [boxeehacks/boxeehack#439]
Hi, i've just updating to the last version of boxee+ in my boxee box. I put all my movies in folders and using the structured explained but I can't get to see the fanart in the boxee even changing of course the style..any suggestions? i used vimediamanager for mac to get the fanart, nfo and folder .jpgs

thanks

**Comment by SendoX** [comment]
folder.jpg  /  fanart.jpg    not jpgs

fanart dont work with Movie name with "Ä/Ö/Ü" in nfo

**Comment by rdlm** [comment]
i said .jpgs meaning plural. 
![Captura de pantalla 2013-02-09 a la s 10 52 35](https://f.cloud.github.com/assets/3515340/141964/7e06db6e-729e-11e2-8f08-1375a3c0bb69.png)

**Comment by SendoX** [comment]
mmmmmhhhh

**Comment by rdlm** [comment]
thanks

**Comment by SendoX** [comment]
special characters can make an error in the whole system. see the movie "Aguila Roja....licula" special characters can make an error in the whole system.With me were not too many Fanarts. I had to remove all files from the special characters. Now go all the fanart pictures

**Comment by rdlm** [comment]
ok, let's could be a problem with that movie specifically. But what's the problem with Avatar? The info inside the nfo is in english just in case so i don't see any problem...

**Comment by SendoX** [comment]
as I said. The problem is sporadic. times, the problem arises, sometimes not.
I had the same problem. not until I had removed all special characters, what problem-that away.

wie gesagt. das problem ist sporadisch. mal tritt das problem auf , mal nicht.
Ich hatte das selbe problem. erst als ich alle sonderzeichen entfernt hatte, was das problem weg.

**Comment by boxeehacks** [comment]
The issue is that it tries to link all movies to their fanart files, but if it fails at some point it stops scanning. This means that if it fails on the Aguila Roja thing then it never continues to Avatar, meaning you'll never see fanart for any movie later in the list. Working on the fix for that, but it's being a bit troublesome :(

**Comment by boxeehacks** [comment]
Have been able to reproduce and fix this. Update coming soon!
