### ISSUE TITLE
Will it work without original remote control

### ISSUE THREAD

**Issue by zalun** [boxeehacks/boxeehack#496]
It's more a question than an issue.

My original remote control is broken - I do use phone "boxee remote apps". This requires boxee to be connected to the home network before I can touch the UI.

Will boxee connect to WiFi straight after installation? What about cable (ethernet)?

**Comment by langluc** [comment]
http://www.amazon.com/Rii-Wireless-Keyboard-Multimedia-Handheld/dp/B004716NFE/ref=sr_1_1?ie=UTF8&qid=1362057556&sr=8-1&keywords=Rii+Touch+240

this is perfect for boxeebox

**Comment by MonkeyWeiti** [comment]
boxee should connect to ethernet straight after installation.
wifi probably not, as you need to check what wireless network it should connect to.
but after setting everything up via ethernet, switching to wifi later should work.

**Comment by chrisjennings** [comment]
I have a follow up question here.  I lost my remote and my boxee was connected via ethernet not wi-fi.  Because of this, none of the app remote options work over ethernet.  And of course I can't connect to wi-fi without a remote to setup the network.  The ol' Catch-22.  Any advice on how to connect a wi-fi remote while on ethernet?

**Comment by zalun** [comment]
@chrisjennings just connect any USB keyboard
