### ISSUE TITLE
Add Audio Output device settings to be set to Airplay capable devices

### ISSUE THREAD

**Issue by maty974** [boxeehacks/boxeehack#57]
If it's possible add the "Audio output device", to be able to set an Airport Express device as output audio device.

like in the default settings window of XBMC : 
http://wiki.xbmc.org/index.php?title=Settings/System#Audio_output

**Comment by boxeehacks** [comment]
If we're really lucky Boxee will roll this feature in their final update. However something like this is not something we can add, because it requires compilation of the Boxee executable, which currently is not possible because we're missing parts of the SDK. As soon as this is possible we'll sync everything with the latest and greatest XBMC, which enables a lot more options...
