### ISSUE TITLE
More replacement options for Featured media

### ISSUE THREAD

**Issue by hessius** [boxeehacks/boxeehack#61]
Jerbob92 has added the ability to replace the featured media section with recently added media, this is great! 

But what would be even better is letting each user decide between the original featured media (as long as it lasts), recently added media or a custom rss feed - preferably with some presets such as latest trailers from traileraddict or latest news clips from cnn etc.

**Comment by boxeehacks** [comment]
Using something like a custom feed will be possible in the future, however it requires a feed in a quite specific (non-RSS) format. Any feeds that get loaded there will pass through the boxee API as well, so this will probably be part of a more extensive replacement of the boxee servers

**Comment by jerbob92** [comment]
Some information on what's possible:
http://forums.boxee.tv/showthread.php?t=15155

**Comment by felipesalomao** [comment]
This really would be great, show and link last added medias would be pratical, because if added program tv we dont need to enter on tv programs to find content..

**Comment by boxeehacks** [comment]
Unfortunately the boxeedb://movies and similar are pretty useless for this, since they are not sorted by recently added. This means that you just get the first few movies that happen to be first in the alphabet.

**Comment by boxeehacks** [comment]
I've added the following:

Boxee Featured (the normal one)
Recently Added with overlays to indicate the type (movie, TVshow or music)
Vimeo staff picks
Youtube featured

Also if a movie is shown in the recently added, and there is fanart available, it will show the fanart, because the posters usually look pretty crap in a landscape box.

**Comment by felipesalomao** [comment]
its included on default hack or should add more modifications ? Would be great have this added default with actual version of Boxee+ hack.

**Comment by boxeehacks** [comment]
These are all in the new 1.2.2 version.

**Comment by krth8** [comment]
"Also if a movie is shown in the recently added, and there is fanart available, it will show the fanart, because the posters usually look pretty crap in a landscape box."

Is it possible to change the aspect of these boxes so that the cover art would look good? It would also be room for more movies on one slide if it did. 

I love the recently added feature so if this could work it would be great!
