### ISSUE TITLE
Last.fm scrobbling

### ISSUE THREAD

**Issue by JasGill** [boxeehacks/boxeehack#610]
Can anyone explain on how to enable last.fm scrobbling from BoxeeBox. @daften could you please help on this, as I saw you created scrobbler for BoxeeBox but now the link you provided is dead !

**Comment by daften** [comment]
I enabling scrobbling with 2 scripts (last.fm and trakt) that ran on my nas and pinged my boxee box. I'd started creating a more universal (external) scrobbler, but since team boxee screwed us by stopping development, I stopped and moved to a RPi with XBMC and then to Plex on a google tv box.
I've also deleted my repositories, since I didn't plan to go back, I thought the original repo's were online, but I can't find them.
Sorry, but I don't think I can help you. Really sorry for that :s
