### ISSUE TITLE
Improved airplay support

### ISSUE THREAD

**Issue by cyberdudePete** [boxeehacks/boxeehack#62]
Current airplay support is unstable. Audio controls tend to freeze if you try to navigate too much. Video also has similar issues.

An improved or replaced airplay subsystem would be great.

**Comment by boxeehacks** [comment]
Unfortunately there is nothing we can do about this. This requires recompiling certain executables, which we currently cannot do due to the Intel SDK missing certain required parts. However many stability issues have been solved in XBMC itself regarding Airplay. When Boxee does their final release, hopefully those stability fixes will also have been incorporated.
