### ISSUE TITLE
Remote Control?

### ISSUE THREAD

**Issue by dmike3** [boxeehacks/boxeehack#95]
Is it possible to have some sort of remote control via VNC?

**Comment by hessius** [comment]
Remote control the box or your computer?
If it's another way of controlling the box check out #92 where mape0661 has got https://github.com/nicholasrobinson/BoxeeBox-PHP-JSONRPC running

**Comment by dmike3** [comment]
Remote control the box like you do with your computer via VNC.

**Comment by jerbob92** [comment]
Not sure if that's even possible, AFAIK the BoxeeBox doesn't even run a window manager.

**Comment by boxeehacks** [comment]
Nope, it's writing graphics directly to the GPU through OpenGL ES. There would be a huge performance overhead trying to read those pixels back out every frame and then running something like a VNC server to stream it. Even if it were technically feasible, it won't run well enough to be usable...

So that'll be a no then ;)
