### ISSUE TITLE
Scheduled/cron shutdown/reboot

### ISSUE THREAD

**Issue by SiIason** [boxeehacks/boxeehack#97]
I use slingbox app for tv (but this affects all app usage) and its great but because it runs as an app when I fall asleep the boxee never goes idle, so screensaver etc can never kickin.

Would be nice to have a cronjob so at 2am it powers down, maybe even powers back on 7am.
Pretty sure this would give a better night sleep without the tv flickering :)

**Comment by boxeehacks** [comment]
Looks like this is more a defect of the slingplayer app than anything else. E.g. the netflix app will allow the screensaver to kick in without any problems. If there's a good use case in the future for cron jobs, it will definitely get considered... but for this issue I'd feel more comfortable fixing the slingplayer app first. Who devved that? maybe someone on the developer forums for boxee apps can help?

http://forums.boxee.tv/forumdisplay.php?f=19

Powering back up at a certain time won't be possible because this needs to be supported by the hardware and boot firmware itself as well.
