### ISSUE TITLE
Screensaver/App timeout/popup "still there" check

### ISSUE THREAD

**Issue by SiIason** [boxeehacks/boxeehack#98]
If I watch a lot of content via apps or if my screensave kicks in then thats it my box is never going to power down and it will sit there churning content. If we think about the youtube app this could be HD format at 3Mb/sec+ and this could be on a couple of boxes, no wonder I'm always over my virgin media cap :/

Would be great if we could have a choosable timeout so that in say 180 minutes (so movies don't get interrupted) boxee asks via popup "Press OK to stay watching" or similar then if we don't click given 60 seconds the box can power down saving money and A LOT of bandwidth.

**Comment by hessius** [comment]
Netflix has something similar which it implements in a nice way, could be used for reference

**Comment by boxeehacks** [comment]
This can now be implemented as a plugin. You can now have a cron job running as a plugin which triggers a python script in XBMC that can do this. I will probably not build this as a standard part of the Boxee+ (too little time, too much to do unfortunately), but have put in the infrastructure so that someone can do this...

**Comment by boxeehacks** [comment]
See also #166 for info on how/why
